server:
  port: 8080

spring:
  application:
    name: Redrive
  datasource:
    url: jdbc:mysql://localhost:3306/redrive
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret-key:

media:
  path: "C:/Users/asus/Documents/Programming/Project/Redrive/Backend/src/main/resources/media/"